### PR TITLE
Work in progress 2016 teacher training deck, but ok to publish now

### PR DESCRIPTION
**Pull request by careful-with-that-axe**
Please do publish at once, no changes except to add a page for our teachers/tas to look at with some more updated information.

### CODE REVIEW

**Comment by lilliealbert** [comment]
I'm a little bit confused about this PR — is the main goal to move from the old slide format to markdown? Since it's kind of a copy-paste of the old slides, it makes it hard to see what's been changed, which makes reviewing it pretty difficult. (When you say "No changes except to add a page for our teachers/tas to look at with some more updated info", do you mean the descriptions of class levels?)

I also think that putting the class levels in the docs instead of making them more easily available from within Bridge Troll is not great — keeping them in sync will be challenging. If we provided a public page on Bridge Troll that could be referenced from the teacher training, would that help accomplish what you're going for?

I definitely want to support updating the teacher training, and if part of that is moving from deck.rb --> markdown, that's cool, but I want to understand this PR better before merging it.

**Comment by careful-with-that-axe** [comment]
Heya Lillie, this is a going to be a new beast.  I used a lot of content from the old slides since I don't have time for a total rewrite and a lot of the content is great in the existing slides.  But it is being totally reordered and more so a pull request to change the existing page would not work.

And I actually didn't change the format of the slides at all, it is following exactly what was already there in more teacher training which was deck.md - so if there was a change it happened before I did this and I followed suit.

I beyond hear you about the levels and am very open to one place where this info lives to avoid multiple updates.  I will modify this once we have that, but for now we don't so we should make do.

We we are putting up an interim page so that the people who were at the class last night can review it, this will eventually be one ridiculously useful page but that transition can't be done overnight. At least not by me though I am devoted to seeing this through. 

I named the link to it work in progress so that the flux nature of this would be apparent to anyone looking at it to hopefully mitigate any confusion.

And by having a separate page we can compare them more easily once the new one is done and I wouldn't have to obscure the original.  But for now I told a bunch of people they would have access to this content, so I would love to see it go up sooner than later.

**Comment by careful-with-that-axe** [comment]
Oh and "no changes" meant I added a new page, didn't change anything that was already there except the link.  Sorry that was confusing, I did the pull request during a short amount of time of a lunch break though the new content has been brewing for a while.

**Comment by lilliealbert** [comment]
So, are you aware that the slide deck basically exists as a single page at RailsBridge.org? http://railsbridge.org/help/teacher-advice

If there isn't any additional info being added in this PR, and it's just getting it all on one page, then I would think that that page would suffice. Let me know.

**Comment by careful-with-that-axe** [comment]
Hi Lillie, this is for actual teacher training and it is a work in progress that I want to share with the teacher/tas that I worked with last night.  Please publish the one page.  I will remove the link so it doesn't confuse people who weren't there.  Anything else at this point is premature.  But after the latest version comes together we can work to get it all on the properly synced/same page.

**Comment by careful-with-that-axe** [comment]
I just pushed that change.  There is a stand alone page now that no one can get to unless they are given the link.  We are really pushing to have the teacher training be more robust and possibly these new slides don't show that yet but they are a start and I want them somewhere that people can see them both as code and for viewing purposes.

**Comment by careful-with-that-axe** [comment]
Did I make myself clear this isn't a reformat and it does not match what is here http://railsbridge.org/help/teacher-advice? It might look like it at a glance, but there are changes and new content. I feel like there is some miscommunication at this point.

**Comment by lilliealbert** [comment]
Yep, it seems like there has definitely been a miscommunication. I'm was definitely confused about whether there has been a change or not to the content, and I'm sorry that I've slowed you down by trying to understand.

I've been at work, so I haven't had a chance to reply to your comments or email yet. I can't deploy the app from my work machine, so if this is something extremely urgent that you need to share with people, would it make sense to put up a gist and link people to that?

**Comment by careful-with-that-axe** [comment]
And sorry about my part in that miscommunication and this being last minute which gives it more urgency that it necessarily should.  I am going to use the gist approach and just close this pull request for now, there will be another one when things get more pulled together.

**Comment by lilliealbert** [comment]
@careful-with-that-axe Another thought — when I was developing the curricula that I've written, I deployed my fork of the docs to Heroku separately to get people's feedback on it. That might be useful to do as you're working on the new teacher training.

**Pull request closed without merging**
