### PR TITLE
updated Xcode command line tools install procedures, fixes #376, fixes #352

### LINKED ISSUE #352: Installfest for mac - Command line tools
The instructions for http://docs.railsbridge.org/installfest/install_xcode_from_app_store are out of date.   The most recent xcode looks like this (without a button to download command line tools):
image

I don't have a mac without command line tools to experiment on, but I'm sure someone at installfest will, make a pull request later. I'm thinking something from this answer will fix it. http://stackoverflow.com/questions/9329243/xcode-4-4-and-later-install-command-line-tools

### LINKED ISSUE #376: Xcode includes command line tools now?
Hi there,

I just got a mac, so I'm installing ruby and all the things, and I noticed that after downloading Xcode 5.1.1 (the latest), it doesn't have the option to install the command line tools.  I tried to see if the new version just comes with those already installed, but couldn't make much headway on that.  So I thought I'd let you know.  

Cheers,
Amy

Edit: I'm on Mavericks with an i7, if that makes any difference.

### PR DESCRIPTION
**Pull request by rurabe**
I was sitting in the volunteer meeting for RailsBridge NYC and thought that this might help for installfests.

The last time I did one of these workshops, everyone was trying to download Xcode at the same time and it made the internet connection crawlllll... going for just the command line tools will help with that and will save space on the students' computers.

I think this is a simpler install process anyway, and it will work for the 10.9 and 10.10 people who are confused when they can't find the option to install it from Xcode.

### CODE REVIEW

**Comment by lilliealbert** [comment]
hey @rurabe, how did this end up going, so many months ago, if you can still remember? :stuck_out_tongue_winking_eye:

**Comment by lilliealbert** [comment]
hey @rurabe, are you planning on attending the installfest at General Assembly this Friday, and also were you planning on using the forked version again? It'd be great to have a better idea of how this set of instructions works for people on 10.6-10.8.

**Comment by rurabe** [comment]
Hey Lillie,

Sorry for the late reply... It seems to be working for everyone I've been
helping. In fact someone just forgot to install it and the rubygems error
suggested that they run xcode-select.

**Comment by dominic** [comment]
Just want to :+1: this concept, but maybe not this PR. At the Oakland Railsbridge installfest, we had some initial confusion with the install from Xcode option not working in Yosemite. It would be great to split the instructions by Mac OS version.

**Comment by tjgrathwell** [comment]
@rurabe @dominic I've committed and deployed a re-mixed version of this as 9e447cd18139cbd5ff76fc7949c8346b354e5e1c and 3b1d81aab4dfa2cd4f1971fb227a3c1a4b6fc944. 

This adds in the `xcode-select` option (now long overdue) while preserving the "download from app store" instructions for anyone who still needs them.

Please comment or PR with any further amendments in this area. It's hard to keep this section straightforward and accurate because unlike a Ruby install, once you install Xcode or the command line tools properly it tends to just be there, more-or-less working properly. Making it hard to remember how you got them installed in the first place.

**Comment by rurabe** [comment]
Sounds good to me

**Comment by dominic** [comment]
Looks great. Thanks @tjgrathwell!

**Pull request closed without merging**
