### PR TITLE
Kyfast/add optional GitHub step

### PR DESCRIPTION
**Pull request by KyFaSt**
I thought it could be nice to include explicit instructions on the the rails bridge installfest docs to set up GitHub :neckbeard:

### CODE REVIEW

**Comment by tjgrathwell** [comment]
Hi @KyFaSt !

This is interesting, but I'm not sure how it will be integrated with the RailsBridge workshop itself. How are you imagining people will use their Github accounts during the workshop?

Currently, the entry point you've made from the 'add an ssh key' seems a little scary, because it's set up as "Create a Heroku account **or** Create a Github account". Since the rest of the installfest assumes you've created a Heroku account, it seems dangerous to phrase it that way because some people might just do the Github part and move on.

Second, within your Github instructions themselves a big focus is adding SSH keys via the github interface, which is technically unnecessary; people could do login/password with SSH. If we're making people add SSH keys, I would want to confirm that it worked either at the bottom of the Github account creation page or during the "get a sticker" step by having students do `ssh -T git@github.com` like on https://help.github.com/articles/generating-ssh-keys/

**Comment by KyFaSt** [comment]
All very good comments @tjgrathwell, thank you for getting back to me so quickly! Let me try to address them each as best I can:

##### How will this be used during the workshop?
I suppose that this addition was somewhat shortsighted of me, I didn't think about including this in the rest of the workshop. I thought including the GitHub setup would make the workshop participants more prepared for coding outside of the workshop, because I really liked how the RB installation steps include heroku setup which can be tricky if you don't have CLI experience.

I could add points to add, commit & push code throughout, but I wouldn't want to do something like that which would change how the workshop operates unless there is consensus that this would be helpful. I think though that it is helpful to be thinking about version history early on and that it doesn't detract in a non-helpful way from learning about Ruby & Rails.

##### Will this cause participants to accidentally skip the heroku step?
Maybe changing the copy to something like "Add version control with GitHub" could reduce the risk of someone skipping the heroku step. If not, would it make sense to move the GitHub step to after the Heroku step? Or, I would be open to any ideas that you or anyone else have about reducing the risk of confusion :bowtie: 

##### Is SSH via GitHub.com necessary? Should we confirm that it works?
I have only ever setup GitHub by adding the SSH keys through web UI, so I'd be happy to make this change but I might need a little direction.

I think you're right, a final step should be added to confirm that GitHub SSH access was setup correctly. I can add that bit right away. I'm not sure what the precedent on this project is but would it be alright to add that in another separate commit? The commit history won't be 'pretty' per se but I don't want to rebase & force push on a public branch unless that's preferred :neckbeard:

**Comment by tjgrathwell** [comment]
Hi @KyFaSt, sorry to take so long replying to this;

I think it's fine to have a page describing how to set up a Github account as long as it's obvious that it's optional and it doesn't diverge too far from the normal flow. To that end, I think it makes sense to add the link somewhere near the bottom of the "Configuring Git" page.

Maybe a section with text like `"Now that you have Git configured properly, you can optionally [Create a Github account](create_a_github_account) to share code with your friends"`

Additionally at the bottom of the create_a_github_account page itself the student should be instructed to run something like `ssh -T git@github.com` to validate that they can connect to Github over SSH.

Usually for pull requests I prefer the history to be as squished-up as possible, so rebasing and force pushing is fine.

**Comment by lilliealbert** [comment]
Wanted to check in if you were still interested in the PR, @KyFaSt? (Or maybe just busy with life?) 

I think having GitHub accounts would be pretty cool for RailsBridge students. :sparkles:

**Comment by KyFaSt** [comment]
@lilliealbert & @tjgrathwell I am still interested in this, but I have been a little busy.

I will patch it up and push again sometime today :bowtie:

**Comment by KyFaSt** [comment]
@tjgrathwell & @lilliealbert I think I have addressed most of the comments with updates to the code. Is there anything else that makes sense to change (or that I have missed)?

**Comment by tjgrathwell** [comment]
Thanks @KyFaSt, I've pushed up your changes with some amendments (b6d6c1a8a16e8d71ddacd2e8f1e3b4b9f89c8ef6) and the change is live in locations such as http://docs.railsbridge.org/installfest/create_a_github_account

The link to the "Create a Github Account" page actually wasn't showing up at the bottom of "Configure Git" because the link text was in a freefloating string without anything like `message` or `div` to render it. It was still showing up in the Table of Contents though because the table of contents is wacky like that.

Feel free to comment back if there's anything about my change you didn't like, or open another PR with more changes if the feeling strikes you.

**Comment by KyFaSt** [comment]
Thanks @tjgrathwell I think with your changes this looks great!

**Pull request merged**
