### PR TITLE
More friendly less scary

### PR DESCRIPTION
**Pull request by SteveBarnett**
Some more things we got from student feedback.

* They didn't know who / what DHH was.
* They found the InstallFest kind of hectic, and would have liked to know that Saturday was going to have a more relaxed pace.
* They found some of the language a little scary.
* They really, **really**, like stickers. :D.

This PR tries to make some of the language more friendly, expand some acronyms, and make the course be more friendly, less scary.

### CODE REVIEW

**Comment by tjgrathwell** [comment]
I like all these changes a lot, I think the sassy language might've been fun at some point but friendliness is better :smile_cat:

Just a couple things:
* Rather than bother to explain who DHH is, I'd rather shorten that overlong sentence completely. Maybe something like "*In fact, you'll type this so much that there's a shortcut for it. Simply typing `rails s`...*"
* Can you rebase and merge those last two commits onto the commits that caused the typos? I think it's better for all the commits to pass the test suite, rather than having a sequence like
 * (c1) Make change
 * (c2) More changes!
 * (c3) Oops, fix tests broken in `c1`

**Comment by SteveBarnett** [comment]
@tjgrathwell Cool cool cool, thank you :). 

* `rails s` explanation shortened
* Much rebasing done (Something I don't do often, so let's hope I haven't messed it up! :grimacing:)

**Comment by tjgrathwell** [comment]
Looks great, thanks! :rocket:

**Comment by SteveBarnett** [comment]
Huzzah! \o/

**Pull request merged**
