### PR TITLE
Add glossary

### PR DESCRIPTION
**Pull request by SteveBarnett**
Something that came up in attendee feedback was language: there's a lot of technical terms / jargon / new words!

An attendee and a TA worked together to create this glossary, which we want to add to the InstallFest (when they're being bombarded with the most new stuff) and the Intro to Rails course (which is the course we run most often).

### CODE REVIEW

**Comment by tjgrathwell** [comment]
If these glossaries are intended to remain the same, rather than duplicating them I would prefer to keep the content in just one of the sites and use the `insert` functionality to include it where it's needed, as seen in some of the JS curricula. For example:

https://github.com/railsbridge/docs/blob/master/sites/en/javascript-to-do-list/javascript-to-do-list.step#L52 

and

https://github.com/railsbridge/docs/blob/master/sites/en/javascript-to-do-list-with-react/javascript-to-do-list-with-react.step#L54

are both references to

https://github.com/railsbridge/docs/blob/master/sites/en/javascript-to-do-list/_lesson_format.md

**Comment by SteveBarnett** [comment]
@tjgrathwell Excellent idea. Don't know why I didn't do that in the first place.

Have pushed that change.

**Comment by tjgrathwell** [comment]
Looks like a good start, it'l be great to get something like this in because people are proposing it after every workshop :)

A couple suggestions:
* I think the item about 'escape sequences' should probably be a backslash (`\`) instead of a slash
* Almost all the items in the "command line" section are something you could actually type into the command line, except `puts`, `=` and `==`. It seems like those should be in a separate "ruby" section (though that might grow very large, if it starts describing all of ruby!)

**Comment by SteveBarnett** [comment]
How about this? 

I've moved the Ruby / Rails stuff to it's own little section. I think it can be short (and not try to cover All The Things of Ruby and Rails) because we just want to cover the stuff in the course (plus one or two other tiny bits).

**Comment by tjgrathwell** [comment]
:rocket: I still think the `=` and `==` don't belong in the "command line" section but close enough!!

**Comment by SteveBarnett** [comment]
Woo! \o/

**Pull request merged**
