### PR TITLE
spelling errors fixed

### PR DESCRIPTION
**Pull request by Eibonic**

### CODE REVIEW

**Comment by tjgrathwell** [comment]
@Eibonic can you amend the commit to fix the issue @lilliealbert noted?

**Comment by Eibonic** [comment]
Ok I changed list's to lists

**Comment by tjgrathwell** [comment]
Hey @Eibonic, I think you got that backwards, both of the `lists` in this changeset should be `list's`.

Also, can you merge these into a single commit instead of creating additional commits?

**Comment by tjgrathwell** [comment]
Committed as 878ef64b986d0f62a47dcb9c1b11636964cbfbd9

**Pull request closed without merging**
