### PR TITLE
Rename intermediate-rails to message-board

### PR DESCRIPTION
**Pull request by lilliealbert**
Ehhhhh????????

### CODE REVIEW

**Comment by lilliealbert** [comment]
Whomp whomp, fixing now

**Comment by tjgrathwell** [comment]
Pretty daring.

If we're to do this, I would also add an entry to the `redirect_sites` in app.rb to preserve existing links: https://github.com/railsbridge/docs/blob/master/app.rb#L94

**Comment by rachelmyers** [comment]
I'm totally on board with this; do we ever indicate difficulty levels or an order to work through things? Will people know that this isn't what they should start with?

**Comment by alexch** [comment]
We could start each course's home page with a schematic or matrix of all the RB doc sites, with suggested prereqs and a big "YOU ARE HERE"

**Comment by jessieay** [comment]
I taught "green" last weekend and wasn't sure which app we should work on. I know suggestotron is the default but didn't really know what it meant to be in the "Green" level. We ended up working on suggestotron and I think it was a bit too easy for a good portion of the class. If we'd had more info on the different apps to work on we may have gone with someone a little harder.

+1 for including a matrix with level / pre reqs and apps to work on.

**Comment by tjgrathwell** [comment]
Alright, I've added the `redirect_sites` addendum myself and deployed this.

Moving discussion about levels, matrices, etc to a new issue: https://github.com/railsbridge/docs/issues/463

**Pull request merged**
