### PR TITLE
Updating basic javascript curriculum

### PR DESCRIPTION
**Pull request by courtney**
After some helpful feedback from our JS workshop in Chattanooga this weekend we made some updates to the beginner JS curriculum. More to be done here but hopefully this helps some folks.

### CODE REVIEW

**Comment by tjgrathwell** [comment]
Hey @wnstn & @courtney, this mostly looks good, here are the issues I've found:

* The intro page has a merge-conflict looking `<<<<<<< HEAD` sitting in the text (seemingly from this commit 0ac114e6266657ccb7ea9aaa44003121c77a7396)

screen shot 2015-03-15 at 8 08 51 pm

* The "lesson 1" page has a header that didn't get processed as markdown correctly (probably an indentation issue). On this page it might be better to send the step titles into the step function, like `step "Stop and Reflect" do`.

screen shot 2015-03-15 at 8 08 57 pm

* (much more subjectively) The content added to Lesson 2 and Lesson 3 are pretty extreme walls of text, which in my experience is hard to integrate into a workshop setting, even if they read well. It may be that the curriculum is better for having them, but ideally they would be more spread out / succinct.

Can you fix up those first two problems and rebase away all the merge commits?

**Comment by courtney** [comment]
@tjgrathwell sorry for the glaring errors. we'll fix those right up and make sure to get rid of the merge commits.

**Comment by tjgrathwell** [comment]
@courtney @wnstn pingin' back to remind y'all to fix this up so it can get incorporated

**Comment by courtney** [comment]
@tjgrathwell @wnstn should be all fixed up now. Fixed up leftover merge cruft and editing first part of lesson to run a bit smoother. Let me know if there is anything else you see.

**Comment by lilliealbert** [comment]
@courtney Do you think you could squash this down into one or two commits?

**Comment by courtney** [comment]
sure!

c

On Sun, Mar 22, 2015 at 10:05 AM, Lillie Chilen <notifications@github.com>
wrote:

> @courtney <https://github.com/courtney> Do you think you could squash
> this down into one or two commits?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/railsbridge/docs/pull/451#issuecomment-84655311>.
>



-- 
Courtney Hemphill
Carbon Five

415-546-0500 x 20 | http://www.carbonfive.com
<https://twitter.com/chemphill>
<http://www.linkedin.com/in/courtneyhemphill>

**Comment by tjgrathwell** [comment]
Looks good, deployed! :rocket: 

There was one more issue with duplicate `steps do` nesting that I've fixed up as 0fcf584fd3424cf5a1e2551878340cbf43efb771

**Pull request merged**
