### PR TITLE
Add tools overview

### PR DESCRIPTION
**Pull request by SteveBarnett**
Hi! [Long time RailsBridger](https://railsbridgecapetown.org/#past-events), first time contributor. :)

One of the things that attendees asked for in the feedback we gathered was more of an overview of the course because. We added:

* Brief explanations in the InstallFest docs of what each tool is (which is **this Pull Request**).
* An [overview presentation](https://github.com/RailsBridge-CapeTown/presentations/blob/master/overview.pdf) that gets done on the InstallFest Friday night explaining: what Ruby, Rails, Git, and Heroku are and how they fit together; how the text editor, terminal, and browser related to each other and what they do.
* The same bits to the [welcome presentation](https://github.com/RailsBridge-CapeTown/presentations/blob/master/welcome.pdf) on Saturday morning.

### CODE REVIEW

**Comment by lilliealbert** [comment]
This is neat! These are really nice, approachable explanations. :smile_cat: 

I think it might be useful to have something like "Don't worry, you don't need to memorize this list!" messaging at the top, since it's so early in the installfest, and people might think they need to start taking notes instead of getting things installed. Whaddya think? 

:panda_face: :palm_tree: :panda_face:

**Comment by SteveBarnett** [comment]
@lilliealbert Great idea! :)

How's this?

> Here's a list of tools you'll be installing. As you go through the workshop, we'll explain what each one is for and how to use it.

I think it reinforces the messaging in other sections of the InstallFest (and the opening presentation): "this is a lot of stuff, yes, but we explain it later. :)"

**Comment by lilliealbert** [comment]
Totes!! :rocket:

**Comment by tjgrathwell** [comment]
:rocket:

**Comment by SteveBarnett** [comment]
\o/

**Pull request merged**
