### PR TITLE
Update programming_with_javascript.step

### PR DESCRIPTION
**Pull request by RoseTHERESA**
Correct one error with grammar (line 81), one with spelling (line 91), and one with explaining arrays (line 92).

### CODE REVIEW

**Comment by tjgrathwell** [comment]
Hi @RoseTHERESA, I think this is all correct except that I don't think you should've changed "first" to "second" in the `slice(1)` example. 

```
> arr =[1,2,3,4]
[1, 2, 3, 4]
> arr.slice(1)
[2, 3, 4]
```

When you .slice(1), it's returning "everything after the first element"; if it was "everything after the second element" then the result array would be [3,4].

You could maybe say "everything from the second element onwards" or many other variations like that, but "everything after the second" seems wrong.

**Comment by RoseTHERESA** [comment]
Yes, of course, it would be everything beginning with the second element, not after. Sorry 'bout that. I think the text as it is says everything to the right of the first element, which is correct. Whichever way you slice it...

**Comment by tjgrathwell** [comment]
Okay, I've merged your amendments + changed the `second` back to `first`.

**Comment by RoseTHERESA** [comment]
:) First time I did this. Maybe see you tomorrow...

**Pull request merged**
