### PR TITLE
Creates Intermediate JavaScript curriculum

### PR DESCRIPTION
**Pull request by raorao**
Students are asked to create a to do list application that consumes an already written and deployed API. HTML and CSS are also pre-written. Modeled after the intro to rails curriculum, it moves very fast and includes a lot of copy and pasting. 

Expects students to have some familiarity with basic programming, although nothing extensive. Intentionally, every line of code students are required to write is included in the tutorial. See curriculum for more details. 

Requirements:
* requires an operational listalous.herokuapp.com (as an API). see on github at https://github.com/raorao/headless_todos.
* asks students to download resources from https://github.com/raorao/IntermediateTodoList .

Sorry for pushing this to the 11th hour! Happy to take any notes, planning on working on this non-stop. Thanks for letting me contribute!

### CODE REVIEW

**Comment by alexch** [comment]
I'm checking this out now... `javascript-to-do-list` passes the syntax check... http://localhost:9292/javascript-to-do-list/ works...

Cool!

You should add a link & description to your new site to `docs/docs.step` so people can find it from <http://docs.railsbridge.org>

Instead of downloading a zip of the HTML skeleton, maybe take out the background png and inline the CSS. Then you could just put a single file into the docs site (or into a PRE block) and make the setup/system much simpler.

Some editorial notes:

* Is "dev tools" the right name or should we call them "developer tools" like the browsers do?
* I'd point out that command-option-J opens the JS console immediately
* "Playing With Javascript" throws a lot of JS and jQuery (not to mention DOM cloning) at the students all at once. Maybe too much for a single lesson. Maybe split it into a few pages?
* AJAX is a hard concept for some people; maybe a diagram would be helpful on the Creating A List overview
* are we sure https://listalous.herokuapp.com/ will be up? what happens if 2 students choose the same list name?

**Comment by raorao** [comment]
thanks, @alexch ! to respond to your comments:

* I’ll add links in the docs/docs.step asap!
* I hear you on the avoidance of zip files, but I want to get students in the habit
of writing JS in a separate file. It would also make the HTML much uglier. That said, 
if you think unzipping would be that big of an issue, I’d be happy to change. 
* Playing with JavaScript is a ton, yes. I like the idea of breaking it into basic JS and jQuery. 
* a Diagram would be awesome! I’m not much of an artist, though. I’ll try my hand this weekend. 
* The app is just on heroku’s free tier, so there’s a chance it will get overloaded by traffic. It may make sense to move it to railsbridge hosting for stability, or to host one locally at the railsbridge event as a fallback. 
* If two students choose the same name, they student will see an error during the ‘creating a list’ lesson. They’ll be prompted to create a list with a unique name. I like that process as a way to play with the network tab -- They’ll have to keep going until they find a unique list.

I’ll add a link to docs/docs.step immediately. Breaking down “playing with JS” and adding a diagram will be a project for this weekend, or for any willing collaborators.

**Comment by tjgrathwell** [comment]
@raorao When porting over the Snake Game Tutorial, I added a feature that allows the docs app to create its own zipfiles. If you create a `/sites/whatever/foo.zip-manifest` with a list of relative paths, a user will retrieve a zipped version of those assets when they access `/sites/whatever/foo.zip`. See for example https://github.com/railsbridge/docs/blob/master/sites/en/javascript-snake-game/js-snake-game-tutorial.zip-manifest

The implementation might be a little shaky (it zips the assets in the temp directory, no caching at all) but it seems to work on Heroku. Might be better for keeping things in sync than having a separate repo.

I'm not too worried about a free-tier CRUD Heroku app blowing up (unless someone DDOSes it) but it will certainly run out of database rows eventually, which would be too bad. I think the free postgres DBs cap out at 10,000 rows.

Options include:
* Mount something like that listalous app **in** the docs app, so that their fates are more intertwined. Doesn't really solve the persistence issue; currently the docs app is on the free tier.
* Provide fallback instructions for running the server locally. Probably much less exciting to students than it living in The Cloud.

I think in the near term the hosted thing is fine.

**Comment by tjgrathwell** [comment]
I ran through this and it seems pretty great, save for some extreme walls of text. Though the Rails curricula also have that. Computers be complicated.

I like all the extra-credit options on the last page. I like the CSS and background. I'm a little scared about the amount of times students are asked to do something that will only show up in the Network tab, but we'll see how that goes.

I noticed the sample HTML file doesn't have a `<doctype>` or `<html>`; probably won't cause any issues but it seems better for the document to be as correct as possible.

Also noticed the lack of semicolons in the JS. Doesn't really bother me (it's less typing after all) but I can imagine others getting into heated chats about it.

I'm pushing this up for now with some amendments (fa2a48c9926941af344c01b18dbafd18371fb1a3) because the idea of keeping two complementary PRs going for too much longer gives me the ooks. But please do keep working on it!

**Comment by raorao** [comment]
Thanks for reviewing and merging, @tjgrathwell ! Responding to your comments:

* I noticed the zip file stuff in the snake game, and I didn't know how to use it. That sounds awesome, and its worth keeping our tutorials in sync. 
* I hear you on the hosting thing. At some point, it might be worth adding instructions for allowing students to run this themselves, so their apps can persist long-term. 
* IMO, I'm excited about the network tab. It's helpful in understanding the AJAX process, and its a tab early devs seem to avoid like the plague. Get them used to it early, I say! 
* You're probably write about the doctype thing. I can put in a tiny PR to solve that. 
*  The lack if semicolons are intentional. I feel like novices shouldn't be worried about it, and debug issues as they come up. The other options IMO we're putting them in every line (which would be tedious for a beginner) or teaching them when to include them (which would have been complicated). Better just to not mention it. 

Anyway, I'll put in a PR to support the doctype thing. and I'd love some help in figuring out the zip file stuff! Thanks again!

**Pull request merged**
