### PR TITLE
Flux addon

### PR DESCRIPTION
**Pull request by akanshmurthy**
I'm adding a Flux lesson (upon request from students and talking to raorao) to the To Do List with React curriculum. Happy to cut it down if it's a bit much.

### CODE REVIEW

**Comment by akanshmurthy** [comment]
PING.

**Comment by lilliealbert** [comment]
@raorao or @tjgrathwell y'all got any opinions about this? 

@akanshmurthy It would be cool if you squashed your commits into a single commit — ideally, the Git history of the project is such that you could check out any given commit and all the tests would pass.

**Comment by akanshmurthy** [comment]
@lilliealbert cool, I just squashed- thanks!

**Comment by akanshmurthy** [comment]
@lilliealbert- I haven't gotten any comments yet so I'm pinging again :)

**Comment by lilliealbert** [comment]
hey @raorao — Do you want to be involved in the evolution of the curriculum you added? I think it'd be fun to get your input, but also, we can move forward with evaluating this addition with you if that's more your speed :car: :dash: :dash:

**Pull request closed without merging**
